FROM node:18

# Install dependencies for canvas
RUN apt-get update && apt-get install -y \
    build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend

# We'll install dependencies at runtime
EXPOSE 8081

CMD ["sh", "-c", "npm install && npm run start"]
