networks:
  l4d2stats-network:
    driver: bridge

services:
  
  l4d2stats-api:
    image: node:18
    container_name: l4d2stats-api
    # ports:
    #   - "${API_PORT}:${API_PORT}"
    volumes:
      - ./website-api:/backend
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WEB_PORT=${API_PORT}
    command: >
      sh -c "apt-get update &&
             apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev &&
             cd /backend &&
             corepack enable &&
             yarn install &&
             yarn run start"
    networks:
      - l4d2stats-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  l4d2stats-ui:
    image: node:18
    container_name: l4d2stats-ui
    volumes:
      - ./website-ui:/frontend
      - ./build-once.sh:/build-once.sh    
    command: sh -c "/build-once.sh"
    networks:
      - l4d2stats-network
    depends_on:
      - l4d2stats-api
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  l4d2stats-nginx:
    image: nginx:alpine
    container_name: l4d2stats-nginx
    # ports:
    #   - "${UI_PORT}:80"
    volumes:
      - ./website-ui/dist:/usr/share/nginx/html
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - API_PORT=${API_PORT}
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    networks:
      - l4d2stats-network
    depends_on:
      - l4d2stats-ui
      - l4d2stats-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

